---
title: "Untitled"
author: "Pablo Zúñiga"
date: "`r Sys.Date()`"
output: html_document
---

```{r,include = F}
prodData <- readxl::read_excel("Grupo 1.xlsx",col_names = TRUE)
str(prodData)
prodData <- prodData[,c(6,10,11,13,14,15,16,18,28,29)]
str(prodData)
prodData$CapLinea <- as.numeric(prodData$CapLinea)
prodData$VelAlim <- as.numeric(prodData$VelAlim)
prodData$TempAc1 <- as.numeric(prodData$TempAc1)
prodData$TempAc2 <- as.numeric(prodData$TempAc2)
prodData$TemExp <- as.numeric(prodData$TemExp)
prodData$PresionCono <- as.numeric(prodData$PresionCono)
prodData$CantKgProd <- as.numeric(prodData$CantKgProd)
prodData$Granulometria <- as.numeric(prodData$Granulometria)
datosX <- as.matrix(prodData[,-c(1,3,9,10)])
str(datosX)
datosY <- prodData[,c(1,3,9,10)]
acc <- yacca::cca(x = datosX,datosY,standardize.scores = TRUE)
summary(acc)
corVarCan  <- data.frame(c(acc$corrsq[1],0,0,0),
                         c(0,acc$corrsq[2],0,0),
                         c(0,0,acc$corrsq[3],0),
                         c(0,0,0,acc$corrsq[4])) # correlacion compartida entre las variables canonicas
colnames(corVarCan) <- c("V1","V2","V3","V4")
row.names(corVarCan) <- c("U1","U2","U3","U4")
(coeficientesX <- acc$xcoef) #coeficioentes de x
(coeficientesY <- acc$ycoef) #coeficientes de Y

#Matriz de correlaciones

matDat <- cbind(datosX,datosY)
corDat <- cor(matDat)
```

Matriz de Correlacion de Los Datos

```{r, echo=F}
knitr::kable(corDat,
             digits = 3,
             align = c(rep("c",10)),
             row.names = T)
```

Correlacion entre las variables Canonicas

```{r,echo=F}
knitr::kable(corVarCan,
             digits = 3,
             align = c(rep("c",4)),
             row.names = T)
```
Combinaciones Lineales

$$\begin{cases} U_{1} = a^{(1)'} X = 7.928811e^{-02}X_{NBatch} -4.668493e^{-04}X_{VelAlim} + 2.292986e^{-04}X_{TempAc1} -4.084578e^{-04}X_{TempAc2} + 9.184041e^{-05}X_{TempExp}+ 1.345316e^{-03}X_{PresionCono}+ \\ V_{1} = b^{(1)'} Y = 2.223206e^{-04}Y_{minOrd} - 8.633673e^{-05}Y_{CapLinea} + 4.599479e^{-05}Y_{CantKgProd} -5.859580e^{-08}Y_{Granulometria}\end{cases}$$


$$\begin{cases} U_{2} = a^{(1)'} X = -0.014618975X_{NBatch} + 0.013521840X_{VelAlim} -0.034504609X_{TempAc1} + 0.012856334X_{TempAc2} + 0.002909447X_{TempExp} - 0.133394786X_{PresionCono}+ \\ V_{2} = b^{(1)'} Y = 5.782826e^{-03}Y_{minOrd} + 8.305839e^{-05}Y_{CapLinea} -2.410697e^{-05}Y_{CantKgProd} -1.823120e^{-03}Y_{Granulometria}\end{cases}$$